# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stoDtWT5eUoJN9I1LdJWvgxi3CbzC3Qm
"""

import os
from bs4 import BeautifulSoup
import requests
import time
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
resource_url = "https://ycharts.com/companies/TSLA/revenues"
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}
class Scraping:

    def __init__(self,resource_url, headers):
        self.resource_url = resource_url
        self.html = None
        self.headers = headers

    def download(self):
        self.html = requests.get(self.resource_url, headers= self.headers)

    def display_html(self):
        #print(self.html.text)
        pass


    def parse_html(self):

        df = pd.DataFrame(columns=["Date", "Revenue"])
        parsed_html = BeautifulSoup(self.html.text, "html.parser")
        output = parsed_html.find_all("table")
        row_zero = output[0].tbody.find_all("tr")[0]
        date = row_zero.find_all("td")[0].text
        revenue = float(row_zero.find_all("td")[1].text.strip().replace("B",""))

        df.loc[0] = [date, revenue]
        temp_list = []
        for row in output[0].tbody.find_all("tr"):
            date = row.find_all("td")[0].text
            revenue = float(row.find_all("td")[1].text.strip().replace("B",""))
            temp_list.append([date,revenue])
        
        scraped_data_df = pd.DataFrame(temp_list,columns = ["Date", "Revenue"])
       # print(scraped_data_df)
        return scraped_data_df
        
comm = sqlite3.connect("Revenue.db")
comm.execute("""DROP TABLE Revenue;""")
comm.execute("""CREATE TABLE Revenue (Date, Revenue);""")

sc = Scraping(resource_url, headers)
sc.download()
sc.display_html()
scraped_data_df = sc.parse_html()
df = pd.DataFrame()

for index, row in scraped_data_df.iterrows():
    date = row["Date"]
    revenue = row["Revenue"]

    print(date)  # Access data using column names
    print(revenue)

print(scraped_data_df)


tesla_tuples = list(scraped_data_df.to_records(index = False))
tesla_tuples[:5]

comm.executemany("INSERT INTO revenue VALUES (?,?)", tesla_tuples)
comm.commit()